/*ES CUANDO LAS VARIABLES Y FUNCIONES SE EJECUTAN ANTES DE QUE SE 
ACTIVE CUALQUIER ARCHIVO DE CODIGO.*/


/*CON ESTO DECLARAMOS UNA VARIABLE*/
var miNombre 



/*CON ESTO INICIALIZAMOS UNA VARIABLE*/
miNombre = "José";

/*EN HOISTING MUCHAS VECES LO QUE PASA ES QUE MANDAMOS A LLAMAR VARIABLES
SIN ANTES HABERLAS DECLARADO*/

console.log(miNombre;)

/*EL CONSOLE LOG ES UNA FUNCION QUE NOS DA EL NAVEGADOR. NOS AYUDA A IMPRIMIR EN LA CONSOLA
LOS RESULTADOS. PODEMOS IMPRIMIR VARIABLES, FUNCIONES, MUCHAS COSAS. HACE QUE PODAMOS VER EN LA CONSOLA MUCHAS COSAS.*/

/*EL ORDEN EN EL NAVEGADOR DEBE SER AL REVES. PRIMERO LA VARIABLE Y DESPUES EL CONSOLE LOG*/

var miNombre = "José";

console.log(miNombre);