/*LOS VALORES NUMERICOS SE ESCRIBEN LOS NUMEROS SOLOS*/
40

/*TEXTO VA CON ""*/

"José Micó"

/*VALOR BULIANO. ES PARA VALIDAR COSAS.*/
true
false

/*VALORES VACIOS. PLACE HOLDER. RESERVADO PARA ALGUNOS TIPOS DE VALORES, QUE SUELEN SER FALTANTES*/
/*SE RECOMIENDA NO USARLO UNDEFINED YA QUE PUEDE TRAER PROBLEMAS*/
null
undefined

/* VALORES PARA OBJETOS O PRIMITIVOS. */

/*ARRAYS, TIPO OBJETO, CON VALORES PRIMITIVOS */ [1,2,3]

/*VALOR TIPO OBJETO */

{nombre:"José"} /*ESTO ES UN OBJETO */
